#' Fit Bayesian model to time-to-event data
#'
#' Fits a Bayesian model to time-to-event (tte) data
#' for the purpose of performing Weibull shape parameter signal detection tests 
#' with \code{\link{bwsp_test}}.
#' 
#'
#' @param datstan named list of data for the stanmodel; output of \code{\link{tte2priordat}}
#' @param chains number of Markov chains to run
#' @param iter total number of iterations per chain (including warmup)
#' @param warmup number of warmup iterations per chain
#' 
#' 
#' @return
#' A list with components:
#' \itemize{
#'   \item \code{fit}: fitted model object; a \code{stanfit} object for \code{"w"} and \code{"pgw"},
#'   or a list of two \code{stanfit} objects (\code{$uncens}, \code{$cens}) for \code{"dw"}
#'   \item \code{args_list}: list of model specifications, including the chosen
#'   time-to-event distribution and prior settings
#' }
#' 
#' 
#' @details 
#' The function applies the \code{\link[rstan]{sampling}} command with the No U-Turn sampler
#' to fit a Bayesian model to tte data.
#' 
#' The posterior is proportional to the likelihood times the prior. 
#' The likelihood used in ML estimation is 
#' \deqn{\mathcal{L}(t) = \prod_{i=1}^N S(t_i)^{1-d_i}\cdot f(t_i)^{d_i}} 
#' with \eqn{S(t)}  being the survival function of the chosen distribution, \eqn{f(t)} the
#' density \insertCite{nikulin2016}{WSPsignal}, and \eqn{(t_i, d_i)} 
#' the (right-censored) tte observations.
#' 
#' Prior and tte distribution are specified in the previous data preparation step
#' with function \code{\link{tte2priordat}}.
#' 
#' 
#' @references 
#' \insertAllCited{}
#' 
#' @examples
#' 
#' head(tte)
#' 
#' # prep the data
#' # we formalize a prior belief (here "no association
#' # between drug and event", therefore prior mean = 1 for shape parameter)
#' # and reformat our tte data to fit the model in the following
#' dat_list = tte2priordat(dat = tte,   # reformat the data
#'                       tte.dist = "w",
#'                       prior.dist = "ll", 
#'                       scale.mean = 1, 
#'                       scale.sd = 10,
#'                       shape.mean = 1, 
#'                       shape.sd = 10)
#' 
#' # model fitting
#' mod = bwsp_model(datstan = dat_list,      # fit the model       
#'                  chains = 4,              
#'                  iter = 110,             # (posterior sample is
#'                  warmup = 10)            # small for demo purpose)
#' mod
#' 
#'
#' @export
#'
#'

bwsp_model = function(datstan,
                      chains = 4,
                      iter = 11000,
                      warmup = 1000){
  # arg checks
  valid_datstan <-
    is.list(datstan) &&
    all(c("standat_list", "args_list") %in% names(datstan)) &&
    is.list(datstan$args_list) &&
    all(c("tte.dist", "prior.dist") %in% names(datstan$args_list))
  
  if (!valid_datstan) {
    stop("Argument 'datstan' must be a list generated by tte2priordat().")
  } 
  
  if (!is.numeric(chains) || chains <= 0)
    stop("Argument 'chains' must be a positive integer.")
  
  if (!is.numeric(iter) || iter <= 0)
    stop("Argument 'iter' must be a positive integer.")
  
  if (!is.numeric(warmup) || warmup < 0 || warmup >= iter)
    stop("Argument 'warmup' must be >= 0 and smaller than 'iter'.")
  
  #
  tte.dist = datstan$args_list$tte.dist
  prior.dist = datstan$args_list$prior.dist
  
  stan.input = datstan$standat_list
  
  if(tte.dist == "w"){
    fit = bwsp_model_w(datstan = stan.input,
                    prior.dist = prior.dist,
                    chains = chains,
                    iter = iter,
                    warmup = warmup)
  }
  else if(tte.dist == "dw"){
    fit = bwsp_model_dw(datstan = stan.input,
                     prior.dist = prior.dist,
                     chains = chains,
                     iter = iter,
                     warmup = warmup)
  }
  else if(tte.dist == "pgw"){
    fit = bwsp_model_pgw(datstan = stan.input,
                      prior.dist = prior.dist,
                      chains = chains,
                      iter = iter,
                      warmup = warmup)
  }
  else{
    stop("Argument tte.dist must be one of 'w', 'dw', or 'pgw'.")
  }
  
  out = list(fit = fit, args_list = datstan$args_list) # args_list for info on tte.dist, prior.dist, prior shape sds
  # printing in tte.dist specific inner fct
  return(out)
}



